<?php
require_once('../../includes/session_check.php');
require_once('../../includes/db_connect.php');

// Get receptionist ID from session
$receptionist_id = $_SESSION['user_id'] ?? null;

if (!$receptionist_id) {
    header("Location: /GYM_MANAGEMENT_SYSTEM/login.php");
    exit();
}

// Initialize variables
$error = '';
$success = '';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $member_id = $_POST['member_id'] ?? '';
    $plan_id = $_POST['plan_id'] ?? '';
    $amount_paid = $_POST['amount_paid'] ?? '';
    $date_of_purchase = $_POST['date_of_purchase'] ?? '';
    $date_of_creation = date('Y-m-d');

    // Validate inputs
    if (empty($member_id) || empty($plan_id) || empty($amount_paid) || empty($date_of_purchase)) {
        $error = "All fields are required";
    } else {
        $stmt = $conn->prepare("INSERT INTO receipt (Member_id, Generated_by, Plan_id, Amount_paid, Date_of_creation, Date_of_purchase)
                                VALUES (?, ?, ?, ?, ?, ?)");
        $stmt->bind_param("iiidss", $member_id, $receptionist_id, $plan_id, $amount_paid, $date_of_creation, $date_of_purchase);

        if ($stmt->execute()) {
            $success = "Receipt generated successfully!";
        } else {
            $error = "Failed to generate receipt: " . $stmt->error;
        }
        $stmt->close();
    }
}

// Fetch active members
$member_query = $conn->prepare("SELECT ID, Name FROM User WHERE User_type = 'Member' ORDER BY Name");
$member_query->execute();
$member_result = $member_query->get_result();

// Fetch active plans
$plan_query = $conn->prepare("SELECT Plan_id, Name, Amount FROM membership_plan WHERE Active = 1 ORDER BY Name");
$plan_query->execute();
$plan_result = $plan_query->get_result();

// Fetch receipts generated by this receptionist
$receipt_query = $conn->prepare("
    SELECT r.Receipt_no, u.Name AS Member_Name, mp.Name AS Plan_Name, r.Amount_paid, r.Date_of_purchase, r.Date_of_creation
    FROM receipt r
    JOIN User u ON r.Member_id = u.ID
    JOIN membership_plan mp ON r.Plan_id = mp.Plan_id
    WHERE r.Generated_by = ?
    ORDER BY r.Date_of_creation DESC
");
$receipt_query->bind_param("i", $receptionist_id);
$receipt_query->execute();
$receipt_result = $receipt_query->get_result();

// Check for preselected member from registration
$preselected_member = $_GET['member_id'] ?? null;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Generate Receipt | Gym Management System</title>
    <style>
        label {
            display: block;
            margin-top: 10px;
        }
        input, select {
            width: 300px;
            padding: 8px;
            margin-top: 5px;
        }
        button {
            margin-top: 15px;
            padding: 10px 20px;
        }
        table {
            border-collapse: collapse;
            margin-top: 30px;
            width: 90%;
        }
        th, td {
            border: 1px solid #444;
            padding: 8px;
        }
        th {
            background-color: #eee;
        }
        .navigation {
            margin-top: 40px;
        }
        .navigation a {
            display: inline-block;
            margin-right: 15px;
        }
        .error {
            color: red;
            margin: 10px 0;
        }
        .success {
            color: green;
            margin: 10px 0;
        }
    </style>
    <script>
        function updateAmount() {
            const select = document.getElementById("plan_id");
            const selectedOption = select.options[select.selectedIndex];
            const amount = selectedOption.getAttribute("data-amount");
            document.getElementById("amount_paid").value = amount;
        }
        
        // Auto-select member if coming from registration
        document.addEventListener('DOMContentLoaded', function() {
            <?php if ($preselected_member): ?>
                const memberSelect = document.querySelector('select[name="member_id"]');
                if (memberSelect) {
                    memberSelect.value = <?php echo json_encode($preselected_member); ?>;
                }
            <?php endif; ?>
        });
    </script>
</head>
<body>

<h2>Generate Receipt</h2>

<?php if (!empty($error)): ?>
    <div class="error"><?php echo htmlspecialchars($error); ?></div>
<?php endif; ?>

<?php if (!empty($success)): ?>
    <div class="success"><?php echo htmlspecialchars($success); ?></div>
<?php endif; ?>

<form method="POST">
    <label for="member_id">Select Member:</label>
    <select name="member_id" required>
        <option value="">-- Select Member --</option>
        <?php while ($row = $member_result->fetch_assoc()): ?>
            <option value="<?= $row['ID'] ?>" <?= ($preselected_member == $row['ID']) ? 'selected' : '' ?>>
                <?= htmlspecialchars($row['Name']) ?> (ID: <?= $row['ID'] ?>)
            </option>
        <?php endwhile; ?>
    </select>

    <label for="plan_id">Select Membership Plan:</label>
    <select name="plan_id" id="plan_id" onchange="updateAmount()" required>
        <option value="">-- Select Plan --</option>
        <?php while ($row = $plan_result->fetch_assoc()): ?>
            <option value="<?= $row['Plan_id'] ?>" data-amount="<?= $row['Amount'] ?>">
                <?= htmlspecialchars($row['Name']) ?> (৳<?= $row['Amount'] ?>)
            </option>
        <?php endwhile; ?>
    </select>

    <label for="amount_paid">Amount Paid (৳):</label>
    <input type="number" step="0.01" name="amount_paid" id="amount_paid" required>

    <label for="date_of_purchase">Date of Purchase:</label>
    <input type="date" name="date_of_purchase" value="<?= date('Y-m-d') ?>" required>

    <button type="submit">Generate Receipt</button>
</form>

<!-- Previously Generated Receipts -->
<?php if ($receipt_result->num_rows > 0): ?>
    <h3>Previously Generated Receipts</h3>
    <table>
        <tr>
            <th>Receipt No</th>
            <th>Member Name</th>
            <th>Plan</th>
            <th>Amount Paid (৳)</th>
            <th>Date of Purchase</th>
            <th>Date of Creation</th>
        </tr>
        <?php while ($receipt = $receipt_result->fetch_assoc()): ?>
            <tr>
                <td><?= $receipt['Receipt_no'] ?></td>
                <td><?= htmlspecialchars($receipt['Member_Name']) ?></td>
                <td><?= htmlspecialchars($receipt['Plan_Name']) ?></td>
                <td>৳<?= number_format($receipt['Amount_paid'], 2) ?></td>
                <td><?= $receipt['Date_of_purchase'] ?></td>
                <td><?= $receipt['Date_of_creation'] ?></td>
            </tr>
        <?php endwhile; ?>
    </table>
<?php else: ?>
    <p>No receipts generated yet.</p>
<?php endif; ?>

<!-- Navigation -->
<div class="navigation">
    <a href="receptionist.php">← Back to Dashboard</a>
    <a href="../../logout.php" style="color: red;">Logout</a>
</div>

</body>
</html>
